version: '3.6'
services:
  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    # expose ports on host machine, only in development
    ports:
      - "5432:5432"
  graphql-engine:
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
volumes:
  pgdata: