version: '3.6'
services:
  postgres:
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    # expose ports on host machine, only in development
    # ports:
    #   - "5432:5432"
  business-logic:
    image: business-logic:dev
    build:
      args:
        NODE_ENV: development
    command: nodemon -L src/index.js
    environment:
      NODE_ENV: development
    volumes:
      - ./business-logic:/usr/app
      - /usr/app/node_modules
volumes:
  pgdata: