version: '3.6'
services:
  postgres:
    volumes:
      - ./docker/postgres:/var/lib/postgresql
  pgadmin:
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
  business-logic:
    image: business-logic:dev
    build:
      args:
        NODE_ENV: development
    command: nodemon -L src/index.js
    environment:
      NODE_ENV: development
    volumes:
      - ./business-logic:/usr/app
      - /usr/app/node_modules
# volumes:
#   postgres:
#   pgadmin: